# -*- coding: utf-8 -*-
"""TableQuiz

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VR2FEASk174JZzG4dRYt6uVyF7vJXZjw
"""

import random

# Number of questions
questions = 10

# Total points
points = 0

# Display welcome message and rules
print("Welcome to Times Table Quiz!")
print(" ")
print("---GAME RULES---")
print(" ")
print("The goal is to answer multiplication problems correctly to earn points!")
print(" ")
print("You start with zero points.")
print(" ")

# Loop to run the quiz for 10 questions
for question in range(questions):
    # Generate two random numbers
    number1 = random.randint(1, 9)
    number2 = random.randint(1, 9)

    # Ask the question
    print(f"Question {question + 1}: What is {number1} x {number2}?")

    # Get the user's answer
    answer = int(input("Your answer: "))

    # Check if the answer is correct
    if answer == number1 * number2:
        print("Correct answer!")
        points += 10  # Add 10 points for correct answer
    else:
        print(f"Wrong answer. The correct answer is {number1 * number2}.")

    # Show the current total points
    print(f"Your total points so far: {points}")
    print(" ")

# Display final score
print(f"Game over! You scored {points} points in total.")